name: Build palc_TrayIcon for Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: palc_TrayIcon

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Dependencies
      run: dotnet restore ${{env.Solution_Name}}

    - name: Build palc
      run: dotnet build ${{env.Solution_Name}} --configuration Release --no-restore

    - name: Zip build
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: release.zip
        path: .
        directory: ${{ env.Solution_Name }}\bin\Release\net8.0-windows\
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{ env.Solution_Name }}\bin\Release\net8.0-windows\release.zip

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        file: ${{ env.Solution_Name }}\bin\Release\net8.0-windows\release.zip
        asset_name: palc_TrayIcon_net8.zip
        body: "Automatically compiled and released with GitHub Actions."
        draft: true
